In [117]:
import pandas as pd
from pathlib import Path

In [118]:
file_path = Path(r"C:\Users\resu\Desktop\Nexora-Health-Caresync-pipline\data")

In [119]:
patient_df = pd.read_csv(file_path/"patients.csv")
encounter_df = pd.read_csv(file_path/"encounters.csv")
condition_df = pd.read_csv(file_path/"conditions.csv")
organization_df = pd.read_csv(file_path/"organizations.csv")
provider_df = pd.read_csv(file_path/"providers.csv")
payer_df = pd.read_csv(file_path/"payers.csv")
patient_df.shape[0]
# patient_df or any of the variable name that store the read csv files this calls your data frame

108

In [120]:
df_list = {
           "Conditions":condition_df,
           "Encounters":encounter_df,
           "Organizations":organization_df,
           "Patients" : patient_df,
           "Payers":payer_df,
           "Providers":provider_df
           }

for key, value in df_list.items():
  print("                                                         ")
  print(f"dataset: {key} ")# when we are print out a particular dataframe. we want to know the name of the exact dataframe we are looking out
  print("====================================================")
  print(f"shape of :{value.shape[0]} rows, {value.shape[1]} columns")
  print("====================================================")
  print(value.head())
  print("====================================================")
  value.info()

dataset: Conditions
====================================================
shape of :3784 rows, 7 columns
====================================================
        START STOP                               PATIENT  \
0  1997-04-22  NaN  a1733070-046a-4506-bba6-47f32652e9d7
1  1997-04-22  NaN  a1733070-046a-4506-bba6-47f32652e9d7
2  1989-01-10  NaN  f9ba83f7-9940-16ae-0854-24bd34bf1843
3  2013-05-14  NaN  a1733070-046a-4506-bba6-47f32652e9d7
4  2014-02-06  NaN  a1733070-046a-4506-bba6-47f32652e9d7

                              ENCOUNTER                  SYSTEM       CODE  \
0  a1733070-046a-4506-13b1-f518d757cdd0  http://snomed.info/sct  224299000
1  a1733070-046a-4506-13b1-f518d757cdd0  http://snomed.info/sct  713458007
2  f9ba83f7-9940-16ae-158c-5cd0e5a140b9  http://snomed.info/sct  160968000
3  a1733070-046a-4506-0d73-cf2822965f28  http://snomed.info/sct  266934004
4  a1733070-046a-4506-175b-fc14062cdb07  http://snomed.info/sct   82423001

                                  DESCRIPTION
0         Received higher education (finding)
1  Lack of access to transportation (finding)
2         Risk activity involvement (finding)
3                 Transport problem (finding)
4                      Chronic pain (finding)
====================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3784 entries, 0 to 3783
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   START        3784 non-null   object
 1   STOP         2818 non-null   object
 2   PATIENT      3784 non-null   object
 3   ENCOUNTER    3784 non-null   object
 4   SYSTEM       3784 non-null   object
 5   CODE         3784 non-null   int64
 6   DESCRIPTION  3784 non-null   object
dtypes: int64(1), object(6)
memory usage: 207.1+ KB

dataset: Encounters
====================================================
shape of :5473 rows, 15 columns
====================================================
                                     Id                 START  \
0  f9ba83f7-9940-16ae-5f88-aea1af242f71  1973-02-01T07:34:23Z
1  a1733070-046a-4506-13b1-f518d757cdd0  1997-04-22T16:12:20Z
2  f9ba83f7-9940-16ae-81d1-8cdb486ca3ad  1973-02-16T21:34:23Z
3  f9ba83f7-9940-16ae-158c-5cd0e5a140b9  1989-01-10T22:34:23Z
4  a1733070-046a-4506-0d73-cf2822965f28  2013-05-14T16:12:20Z

                   STOP                               PATIENT  \
0  1973-02-01T07:49:23Z  f9ba83f7-9940-16ae-0854-24bd34bf1843
1  1997-04-22T16:59:47Z  a1733070-046a-4506-bba6-47f32652e9d7
2  1973-02-16T21:49:23Z  f9ba83f7-9940-16ae-0854-24bd34bf1843
3  1989-01-10T22:49:23Z  f9ba83f7-9940-16ae-0854-24bd34bf1843
4  2013-05-14T17:09:30Z  a1733070-046a-4506-bba6-47f32652e9d7

                           ORGANIZATION                              PROVIDER  \
0  497f39dd-280e-3d58-af5b-c5e3a3a09b10  2352c51f-5dce-383b-adbf-bf5cc1f1c4d7
1  c64c848c-0315-3115-87fa-80c360bb6a73  35b13cfd-13a0-34e4-a83d-32af4b12344a
2  497f39dd-280e-3d58-af5b-c5e3a3a09b10  2352c51f-5dce-383b-adbf-bf5cc1f1c4d7
3  f22bc2ac-f8bd-3f9f-9a40-93db37639d3f  b13a2be9-5dba-3041-b1c6-62ff62c512ea
4  c64c848c-0315-3115-87fa-80c360bb6a73  35b13cfd-13a0-34e4-a83d-32af4b12344a

                                  PAYER ENCOUNTERCLASS       CODE  \
0  e03e23c9-4df1-3eb6-a62d-f70f02301496     ambulatory  185347001
1  df166300-5a78-3502-a46a-832842197811       wellness  162673000
2  e03e23c9-4df1-3eb6-a62d-f70f02301496     ambulatory  185347001
3  e03e23c9-4df1-3eb6-a62d-f70f02301496       wellness  410620009
4  df166300-5a78-3502-a46a-832842197811       wellness  162673000

                                  DESCRIPTION  BASE_ENCOUNTER_COST  \
0           Encounter for problem (procedure)                85.55
1  General examination of patient (procedure)               136.80
2           Encounter for problem (procedure)                85.55
3                Well child visit (procedure)               136.80
4  General examination of patient (procedure)               136.80

   TOTAL_CLAIM_COST  PAYER_COVERAGE   REASONCODE  \
0             85.55            0.00  256355007.0
1            704.20          554.20          NaN
2             85.55            0.00  609328004.0
3            704.20            0.00          NaN
4           1716.16         1616.16          NaN

                REASONDESCRIPTION
0         Glycine max (substance)
1                             NaN
2  Allergic disposition (finding)
3                             NaN
4                             NaN
====================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5473 entries, 0 to 5472
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   5473 non-null   object
 1   START                5473 non-null   object
 2   STOP                 5473 non-null   object
 3   PATIENT              5473 non-null   object
 4   ORGANIZATION         5473 non-null   object
 5   PROVIDER             5473 non-null   object
 6   PAYER                5473 non-null   object
 7   ENCOUNTERCLASS       5473 non-null   object
 8   CODE                 5473 non-null   int64
 9   DESCRIPTION          5473 non-null   object
 10  BASE_ENCOUNTER_COST  5473 non-null   float64
 11  TOTAL_CLAIM_COST     5473 non-null   float64
 12  PAYER_COVERAGE       5473 non-null   float64
 13  REASONCODE           3122 non-null   float64
 14  REASONDESCRIPTION    3122 non-null   object
dtypes: float64(4), int64(1), object(10)
memory usage: 641.5+ KB

dataset: Organizations
====================================================
shape of :278 rows, 11 columns
====================================================
                                     Id  \
0  74ab949d-17ac-3309-83a0-13b4405c66aa
1  17a4bae5-8b64-34d7-8144-b428be027bd0
2  e09d4c49-c2ef-3b0f-9a46-3719d9219306
3  ae88fd02-4911-3625-9e97-85b626ed3b0b
4  ab701a70-a658-340e-8f69-ee196a7d40c6

                                                NAME  \
0                        Fitchburg Outpatient Clinic
1                                      NURSE ON CALL
2  UMASS MEMORIAL HEALTHALLIANCE CLINTON HOSPITAL...
3                   FAIRHAVEN HEALTHCARE CENTER INC.
4             CAREWELL URGENT CARE CENTERS OF MA  PC

                      ADDRESS        CITY STATE       ZIP        LAT  \
0             881 Main Street   Fitchburg    MA      1420  42.586487
1  512 MAIN STREET  SUITE 211  SHREWSBURY    MA  15456406  42.295110
2              60 HOSPITAL RD  LEOMINSTER    MA  14533290  42.540319
3              476 VARNUM AVE      LOWELL    MA  18542122  42.644379
4                 484 RTE 134   WORCESTER    MA  16071728  42.262562

         LON                         PHONE  REVENUE  UTILIZATION
0 -71.805210  978-342-9781 Or 978-342-9781      0.0          125
1 -71.718085                    5088451232      0.0            5
2 -71.763130                    9784662000      0.0           83
3 -71.347220                    9784583388      0.0            1
4 -71.801888                    5086947901      0.0           18
====================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           278 non-null    object
 1   NAME         278 non-null    object
 2   ADDRESS      278 non-null    object
 3   CITY         278 non-null    object
 4   STATE        278 non-null    object
 5   ZIP          278 non-null    int64
 6   LAT          278 non-null    float64
 7   LON          278 non-null    float64
 8   PHONE        278 non-null    object
 9   REVENUE      278 non-null    float64
 10  UTILIZATION  278 non-null    int64
dtypes: float64(3), int64(2), object(6)
memory usage: 24.0+ KB

dataset: Patients
====================================================
shape of :108 rows, 28 columns
====================================================
                                     Id   BIRTHDATE   DEATHDATE          SSN  \
0  a1733070-046a-4506-bba6-47f32652e9d7  1979-02-20         NaN  999-14-9549
1  f9ba83f7-9940-16ae-0854-24bd34bf1843  1971-11-23         NaN  999-86-7840
2  fc2d1fb9-862d-a60c-581a-519f5470d866  1975-09-16         NaN  999-93-4967
3  5a1b2463-6dbf-ff69-4ab9-fbc24841b9fd  2005-10-30  2008-03-09  999-90-2978
4  50834d5b-3074-9f8b-833e-e32a1004126d  1980-07-12         NaN  999-14-3925

     DRIVERS    PASSPORT PREFIX       FIRST      MIDDLE          LAST  ...  \
0  S99994775  X74721768X    Mr.    Donte636     Elmo857   Daugherty69  ...
1  S99961203  X51581530X   Mrs.    Ashlee14  Catrina144      Tromp100  ...
2  S99920007  X43158821X   Mrs.   Eartha927  Leanora120      Kulas532  ...
3        NaN         NaN    NaN  Ariadna374   Isabel214  Fernández399  ...
4  S99972845  X90441215X    Mr.    Jesse626  Brendan864     Carter549  ...

         CITY          STATE             COUNTY     FIPS   ZIP        LAT  \
0      Boston  Massachusetts     Suffolk County  25025.0  2124  42.354249
1  Barnstable  Massachusetts  Barnstable County  25001.0  2673  41.706016
2   Wakefield  Massachusetts   Middlesex County  25017.0  1880  42.483985
3      Revere  Massachusetts     Suffolk County  25025.0  2151  42.372662
4      Quincy  Massachusetts     Norfolk County  25021.0  2169  42.317311

         LON HEALTHCARE_EXPENSES HEALTHCARE_COVERAGE INCOME
0 -71.068778            12223.69           173583.25  16400
1 -70.311956           539230.03           737140.75  93948
2 -71.034461           499804.16          1376278.98  77604
3 -70.954338              872.39            41094.85  26313
4 -71.054110            72235.91            15613.10  78102

[5 rows x 28 columns]
====================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   108 non-null    object
 1   BIRTHDATE            108 non-null    object
 2   DEATHDATE            9 non-null      object
 3   SSN                  108 non-null    object
 4   DRIVERS              85 non-null     object
 5   PASSPORT             78 non-null     object
 6   PREFIX               82 non-null     object
 7   FIRST                108 non-null    object
 8   MIDDLE               82 non-null     object
 9   LAST                 108 non-null    object
 10  SUFFIX               1 non-null      object
 11  MAIDEN               19 non-null     object
 12  MARITAL              65 non-null     object
 13  RACE                 108 non-null    object
 14  ETHNICITY            108 non-null    object
 15  GENDER               108 non-null    object
 16  BIRTHPLACE           108 non-null    object
 17  ADDRESS              108 non-null    object
 18  CITY                 108 non-null    object
 19  STATE                108 non-null    object
 20  COUNTY               108 non-null    object
 21  FIPS                 87 non-null     float64
 22  ZIP                  108 non-null    int64
 23  LAT                  108 non-null    float64
 24  LON                  108 non-null    float64
 25  HEALTHCARE_EXPENSES  108 non-null    float64
 26  HEALTHCARE_COVERAGE  108 non-null    float64
 27  INCOME               108 non-null    int64
dtypes: float64(5), int64(2), object(21)
memory usage: 23.8+ KB

dataset: Payers
====================================================
shape of :10 rows, 22 columns
====================================================
                                     Id                    NAME   OWNERSHIP  \
0  a735bf55-83e9-331a-899d-a82a60b9f60c                Medicare  GOVERNMENT
1  df166300-5a78-3502-a46a-832842197811                Medicaid  GOVERNMENT
2  d18ef2e6-ef40-324c-be54-34a5ee865625           Dual Eligible  GOVERNMENT
3  26aab0cd-6aba-3e1b-ac5b-05c8867e762c                  Humana     PRIVATE
4  b046940f-1664-3047-bca7-dfa76be352a4  Blue Cross Blue Shield     PRIVATE

   ADDRESS  CITY  STATE_HEADQUARTERED  ZIP  PHONE  AMOUNT_COVERED  \
0      NaN   NaN                  NaN  NaN    NaN      4746079.19
1      NaN   NaN                  NaN  NaN    NaN      8189171.81
2      NaN   NaN                  NaN  NaN    NaN      1669718.18
3      NaN   NaN                  NaN  NaN    NaN      4481904.63
4      NaN   NaN                  NaN  NaN    NaN      3627799.73

   AMOUNT_UNCOVERED  ...  UNCOVERED_ENCOUNTERS  COVERED_MEDICATIONS  \
0         253947.29  ...                     0                 2069
1         199955.82  ...                     0                  853
2          53363.38  ...                     0                 1256
3        3006027.28  ...                     0                 1224
4        1379866.78  ...                     0                  344

   UNCOVERED_MEDICATIONS  COVERED_PROCEDURES  UNCOVERED_PROCEDURES  \
0                      0                4380                     0
1                      0                5533                     0
2                      0                1872                     0
3                      0                5873                     0
4                      0                2580                     0

   COVERED_IMMUNIZATIONS  UNCOVERED_IMMUNIZATIONS  UNIQUE_CUSTOMERS  QOLS_AVG  \
0                    451                        0                33  0.719799
1                    974                        0                41  0.938123
2                    107                        0                 9  0.770413
3                   1026                        0                22  0.958772
4                    506                        0                42  0.508784

   MEMBER_MONTHS
0           4356
1           7296
2            948
3           9612
4           7404

[5 rows x 22 columns]
====================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       10 non-null     object
 1   NAME                     10 non-null     object
 2   OWNERSHIP                10 non-null     object
 3   ADDRESS                  0 non-null      float64
 4   CITY                     0 non-null      float64
 5   STATE_HEADQUARTERED      0 non-null      float64
 6   ZIP                      0 non-null      float64
 7   PHONE                    0 non-null      float64
 8   AMOUNT_COVERED           10 non-null     float64
 9   AMOUNT_UNCOVERED         10 non-null     float64
 10  REVENUE                  10 non-null     float64
 11  COVERED_ENCOUNTERS       10 non-null     int64
 12  UNCOVERED_ENCOUNTERS     10 non-null     int64
 13  COVERED_MEDICATIONS      10 non-null     int64
 14  UNCOVERED_MEDICATIONS    10 non-null     int64
 15  COVERED_PROCEDURES       10 non-null     int64
 16  UNCOVERED_PROCEDURES     10 non-null     int64
 17  COVERED_IMMUNIZATIONS    10 non-null     int64
 18  UNCOVERED_IMMUNIZATIONS  10 non-null     int64
 19  UNIQUE_CUSTOMERS         10 non-null     int64
 20  QOLS_AVG                 10 non-null     float64
 21  MEMBER_MONTHS            10 non-null     int64
dtypes: float64(9), int64(10), object(3)
memory usage: 1.8+ KB

dataset: Providers
====================================================
shape of :278 rows, 13 columns
====================================================
                                     Id                          ORGANIZATION  \
0  5a26622e-a116-3ad0-9175-53a9b54ea558  74ab949d-17ac-3309-83a0-13b4405c66aa
1  0cb55105-b752-3f2d-aee8-6363e562091a  17a4bae5-8b64-34d7-8144-b428be027bd0
2  dcf488b6-def4-3dfe-b0cc-e6209fa474f8  e09d4c49-c2ef-3b0f-9a46-3719d9219306
3  03cef1fd-0893-36cf-b2dd-1afc00a66a88  ae88fd02-4911-3625-9e97-85b626ed3b0b
4  a0aa193d-bbc6-3046-9a66-982a18a4c8a6  ab701a70-a658-340e-8f69-ee196a7d40c6

                    NAME GENDER        SPECIALITY                     ADDRESS  \
0   Gabriel934 Reilly981      F  GENERAL PRACTICE             881 Main Street
1     Lindsay928 Ward668      M  GENERAL PRACTICE  512 MAIN STREET  SUITE 211
2      Ronald408 Emard19      F  GENERAL PRACTICE              60 HOSPITAL RD
3  Cherrie404 Farrell962      F  GENERAL PRACTICE              476 VARNUM AVE
4      Bud153 Parisian75      M  GENERAL PRACTICE                 484 RTE 134

         CITY STATE       ZIP        LAT        LON  ENCOUNTERS  PROCEDURES
0   Fitchburg    MA      1420  42.586487 -71.805210         125           0
1  SHREWSBURY    MA  15456406  42.295110 -71.718085           5           0
2  LEOMINSTER    MA  14533290  42.540319 -71.763130          83           0
3      LOWELL    MA  18542122  42.644379 -71.347220           1           0
4   WORCESTER    MA  16071728  42.262562 -71.801888          18           0
====================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            278 non-null    object
 1   ORGANIZATION  278 non-null    object
 2   NAME          278 non-null    object
 3   GENDER        278 non-null    object
 4   SPECIALITY    278 non-null    object
 5   ADDRESS       278 non-null    object
 6   CITY          278 non-null    object
 7   STATE         278 non-null    object
 8   ZIP           278 non-null    int64
 9   LAT           278 non-null    float64
 10  LON           278 non-null    float64
 11  ENCOUNTERS    278 non-null    int64
 12  PROCEDURES    278 non-null    int64
dtypes: float64(2), int64(3), object(8)
memory usage: 28.4+ KB

In [121]:
condition_df.head(2)

,START,STOP,PATIENT,ENCOUNTER,SYSTEM,CODE,DESCRIPTION
0,1997-04-22,NaN,a1733070-046a-4506-bba6-47f32652e9d7,a1733070-046a-4506-13b1-f518d757cdd0,http://snomed.info/sct,224299000,Received higher education (finding)
1,1997-04-22,NaN,a1733070-046a-4506-bba6-47f32652e9d7,a1733070-046a-4506-13b1-f518d757cdd0,http://snomed.info/sct,713458007,Lack of access to transportation (finding)

In [122]:
encounter_df.head(2)

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,f9ba83f7-9940-16ae-5f88-aea1af242f71,1973-02-01T07:34:23Z,1973-02-01T07:49:23Z,f9ba83f7-9940-16ae-0854-24bd34bf1843,497f39dd-280e-3d58-af5b-c5e3a3a09b10,2352c51f-5dce-383b-adbf-bf5cc1f1c4d7,e03e23c9-4df1-3eb6-a62d-f70f02301496,ambulatory,185347001,Encounter for problem (procedure),85.55,85.55,0.0,256355007.0,Glycine max (substance)
1,a1733070-046a-4506-13b1-f518d757cdd0,1997-04-22T16:12:20Z,1997-04-22T16:59:47Z,a1733070-046a-4506-bba6-47f32652e9d7,c64c848c-0315-3115-87fa-80c360bb6a73,35b13cfd-13a0-34e4-a83d-32af4b12344a,df166300-5a78-3502-a46a-832842197811,wellness,162673000,General examination of patient (procedure),136.80,704.20,554.2,NaN,NaN

In [123]:
organization_df.head(2)

,Id,NAME,ADDRESS,CITY,STATE,ZIP,LAT,LON,PHONE,REVENUE,UTILIZATION
0,74ab949d-17ac-3309-83a0-13b4405c66aa,Fitchburg Outpatient Clinic,881 Main Street,Fitchburg,MA,1420,42.586487,-71.805210,978-342-9781 Or 978-342-9781,0.0,125
1,17a4bae5-8b64-34d7-8144-b428be027bd0,NURSE ON CALL,512 MAIN STREET SUITE 211,SHREWSBURY,MA,15456406,42.295110,-71.718085,5088451232,0.0,5

In [124]:

patient_df.head(2)

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,a1733070-046a-4506-bba6-47f32652e9d7,1979-02-20,NaN,999-14-9549,S99994775,X74721768X,Mr.,Donte636,Elmo857,Daugherty69,...,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400
1,f9ba83f7-9940-16ae-0854-24bd34bf1843,1971-11-23,NaN,999-86-7840,S99961203,X51581530X,Mrs.,Ashlee14,Catrina144,Tromp100,...,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948

In [125]:
payer_df.head(2)

,Id,NAME,OWNERSHIP,ADDRESS,CITY,STATE_HEADQUARTERED,ZIP,PHONE,AMOUNT_COVERED,AMOUNT_UNCOVERED,...,UNCOVERED_ENCOUNTERS,COVERED_MEDICATIONS,UNCOVERED_MEDICATIONS,COVERED_PROCEDURES,UNCOVERED_PROCEDURES,COVERED_IMMUNIZATIONS,UNCOVERED_IMMUNIZATIONS,UNIQUE_CUSTOMERS,QOLS_AVG,MEMBER_MONTHS
0,a735bf55-83e9-331a-899d-a82a60b9f60c,Medicare,GOVERNMENT,NaN,NaN,NaN,NaN,NaN,4746079.19,253947.29,...,0,2069,0,4380,0,451,0,33,0.719799,4356
1,df166300-5a78-3502-a46a-832842197811,Medicaid,GOVERNMENT,NaN,NaN,NaN,NaN,NaN,8189171.81,199955.82,...,0,853,0,5533,0,974,0,41,0.938123,7296

In [126]:
patient_df.head(2)

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,a1733070-046a-4506-bba6-47f32652e9d7,1979-02-20,NaN,999-14-9549,S99994775,X74721768X,Mr.,Donte636,Elmo857,Daugherty69,...,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400
1,f9ba83f7-9940-16ae-0854-24bd34bf1843,1971-11-23,NaN,999-86-7840,S99961203,X51581530X,Mrs.,Ashlee14,Catrina144,Tromp100,...,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948

In [127]:
#making a copy of the DataFrame we wwant to work on for version control.
clean_patient_df = patient_df.copy(deep=True)

In [128]:
clean_patient_df.head(2)

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,a1733070-046a-4506-bba6-47f32652e9d7,1979-02-20,NaN,999-14-9549,S99994775,X74721768X,Mr.,Donte636,Elmo857,Daugherty69,...,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400
1,f9ba83f7-9940-16ae-0854-24bd34bf1843,1971-11-23,NaN,999-86-7840,S99961203,X51581530X,Mrs.,Ashlee14,Catrina144,Tromp100,...,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948

In [129]:
# we want to perfrom transformation on all the columns. and this applies to all the columns with UUID. Trim the ID column to retain the last element when splitted by -. str.split is a string method
clean_patient_df["Id"] = clean_patient_df["Id"].str.split("-").str[4]
clean_patient_df.head(2)

#In Python, str[-1] outputs the last character of a string. For example, if s = "hello", then s[-1] returns "o"

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,47f32652e9d7,1979-02-20,NaN,999-14-9549,S99994775,X74721768X,Mr.,Donte636,Elmo857,Daugherty69,...,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400
1,24bd34bf1843,1971-11-23,NaN,999-86-7840,S99961203,X51581530X,Mrs.,Ashlee14,Catrina144,Tromp100,...,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948

In [130]:
# we want to convert a data stored in "BIRTHDATE" column's from object to datetime format. handling errorrs by using "errors='coerce'" to coerce invalid formats to NaT
clean_patient_df["BIRTHDATE"] = pd.to_datetime(clean_patient_df["BIRTHDATE"], errors='coerce')

In [131]:
#convert "DEATHDATE" to date time format. handling errors, like invalid data enteries in the column using "errors = corece" which replaces the invalid value with NaT(not a time).
clean_patient_df["DEATHDATE"] = pd.to_datetime(clean_patient_df["DEATHDATE"], errors="coerce" )

In [132]:
clean_patient_df.head(2) #calling the dataframe we see what NaN has change to NaT

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,47f32652e9d7,1979-02-20,NaT,999-14-9549,S99994775,X74721768X,Mr.,Donte636,Elmo857,Daugherty69,...,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400
1,24bd34bf1843,1971-11-23,NaT,999-86-7840,S99961203,X51581530X,Mrs.,Ashlee14,Catrina144,Tromp100,...,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948

In [133]:
#implement the PHI or PIP rules for our dataset. drop ssn, drivers, passport and suffix columns from the dataframe as they are not needed for further analysis.
clean_patient_df.drop(columns=["SSN", "DRIVERS", "PASSPORT","PREFIX"], inplace=True)# inplace = True. inplace: Makes changes in original Data Frame if True.

In [134]:
#strip off the numbers in the first, middle and last name columns to retain only the alphabetic characters. 
#clean_patient_df["FIRST"] = clean_patient_df["FIRST"].str.replace(r"\d+"," ", regex= True)
#"[0-9]+" → finds one or more numbers
#"" → replaces those numbers with nothing
#regex=True → tells pandas to treat "[0-9]+" as a regular expression
clean_patient_df["FIRST"] = clean_patient_df["FIRST"].str.replace("[0-9]+", "",regex= True)
clean_patient_df["MIDDLE"] = clean_patient_df["MIDDLE"].str.replace("[0-9]+", "",regex= True)
clean_patient_df["LAST"] = clean_patient_df["LAST"].str.replace("[0-9]+", "",regex= True)

In [135]:
clean_patient_df["FIRST"].head()

0      Donte
1     Ashlee
2     Eartha
3    Ariadna
4      Jesse
Name: FIRST, dtype: object

In [136]:
# Combine first, middle and last name columns into a single columns into a single column called "FULL NAME"
clean_patient_df["FULL_NAME"] = clean_patient_df[["FIRST","MIDDLE","LAST"]].apply(lambda x: " ".join(x.dropna()), axis=1 )

In [137]:
#drop suffix and maiden name columns as they are not needed for further analysis.
clean_patient_df.drop(columns=["FIRST","MIDDLE","LAST","SUFFIX","MAIDEN"], inplace=True)

In [ ]:
# (Some martial status are not known, so what can we do about does missing data): We can replace all missing value Marital status column is not 
clean_patient_df["MARITAL"] = clean_patient_df["MARITAL"].fillna("Unknown")
df
#You don't need inplace=True here because you're explicitly assigning the result back to the column.

In [154]:
clean_patient_df.head()

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,FULL_NAME
0,47f32652e9d7,1979-02-20,NaT,M,white,nonhispanic,M,Berkley Massachusetts US,1062 Halvorson Underpass,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400,Donte Elmo Daugherty
1,24bd34bf1843,1971-11-23,NaT,D,white,nonhispanic,F,Quincy Massachusetts US,1019 Reilly Orchard Apt 29,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948,Ashlee Catrina Tromp
2,519f5470d866,1975-09-16,NaT,M,white,nonhispanic,F,Dedham Massachusetts US,810 Wiegand Boulevard Suite 78,Wakefield,Massachusetts,Middlesex County,25017.0,1880,42.483985,-71.034461,499804.16,1376278.98,77604,Eartha Leanora Kulas
3,fbc24841b9fd,2005-10-30,2008-03-09,Unknown,asian,hispanic,F,Wesley Saint Andrew Parish DM,1090 Runte Dam Apt 25,Revere,Massachusetts,Suffolk County,25025.0,2151,42.372662,-70.954338,872.39,41094.85,26313,Ariadna Isabel Fernández
4,e32a1004126d,1980-07-12,NaT,M,white,nonhispanic,M,Sunderland Massachusetts US,421 Reilly Rest,Quincy,Massachusetts,Norfolk County,25021.0,2169,42.317311,-71.054110,72235.91,15613.10,78102,Jesse Brendan Carter

In [157]:
clean_patient_df["MARITAL"].value_counts()

MARITAL
Unknown    43
M          38
S          14
D          12
W           1
Name: count, dtype: int64

In [ ]:
# WE CAN USE EXPLORATORY DATA ANAYLSIS TO CHECK IF THOSE WHO HAVE UNKNOWN MARITAL STATUS ARE STILL ALIVE.
#print out a list out a list of all unknown marital status that the deathdate is not null, which means the patient is dead but the martial status is unknown
clean_patient_df[(clean_patient_df["MARITAL"] == "Unknown") & (clean_patient_df["DEATHDATE"].notnull())]

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,FULL_NAME
3,fbc24841b9fd,2005-10-30,2008-03-09,Unknown,asian,hispanic,F,Wesley Saint Andrew Parish DM,1090 Runte Dam Apt 25,Revere,Massachusetts,Suffolk County,25025.0,2151,42.372662,-70.954338,872.39,41094.85,26313,Ariadna Isabel Fernández

In [ ]:
# Standardize the "RACE", "ETHNICITY" columns by converting all values to title case (first letter capitalized) for consistency
clean_patient_df["RACE"] = clean_patient_df["RACE"].str.title()
clean_patient_df["ETHNICITY"] = clean_patient_df["ETHNICITY"].str.title()

ETHNICITY
Nonhispanic    91
Hispanic       17
Name: count, dtype: int64

In [169]:
clean_patient_df.head(5)

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,FULL_NAME
0,47f32652e9d7,1979-02-20,NaT,M,White,Nonhispanic,M,Berkley Massachusetts US,1062 Halvorson Underpass,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400,Donte Elmo Daugherty
1,24bd34bf1843,1971-11-23,NaT,D,White,Nonhispanic,F,Quincy Massachusetts US,1019 Reilly Orchard Apt 29,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948,Ashlee Catrina Tromp
2,519f5470d866,1975-09-16,NaT,M,White,Nonhispanic,F,Dedham Massachusetts US,810 Wiegand Boulevard Suite 78,Wakefield,Massachusetts,Middlesex County,25017.0,1880,42.483985,-71.034461,499804.16,1376278.98,77604,Eartha Leanora Kulas
3,fbc24841b9fd,2005-10-30,2008-03-09,Unknown,Asian,Hispanic,F,Wesley Saint Andrew Parish DM,1090 Runte Dam Apt 25,Revere,Massachusetts,Suffolk County,25025.0,2151,42.372662,-70.954338,872.39,41094.85,26313,Ariadna Isabel Fernández
4,e32a1004126d,1980-07-12,NaT,M,White,Nonhispanic,M,Sunderland Massachusetts US,421 Reilly Rest,Quincy,Massachusetts,Norfolk County,25021.0,2169,42.317311,-71.054110,72235.91,15613.10,78102,Jesse Brendan Carter

In [147]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   108 non-null    object
 1   BIRTHDATE            108 non-null    object
 2   DEATHDATE            9 non-null      object
 3   SSN                  108 non-null    object
 4   DRIVERS              85 non-null     object
 5   PASSPORT             78 non-null     object
 6   PREFIX               82 non-null     object
 7   FIRST                108 non-null    object
 8   MIDDLE               82 non-null     object
 9   LAST                 108 non-null    object
 10  SUFFIX               1 non-null      object
 11  MAIDEN               19 non-null     object
 12  MARITAL              65 non-null     object
 13  RACE                 108 non-null    object
 14  ETHNICITY            108 non-null    object
 15  GENDER               108 non-null    object
 16  BIRTHPLACE           108 non-null    object
 17  ADDRESS              108 non-null    object
 18  CITY                 108 non-null    object
 19  STATE                108 non-null    object
 20  COUNTY               108 non-null    object
 21  FIPS                 87 non-null     float64
 22  ZIP                  108 non-null    int64
 23  LAT                  108 non-null    float64
 24  LON                  108 non-null    float64
 25  HEALTHCARE_EXPENSES  108 non-null    float64
 26  HEALTHCARE_COVERAGE  108 non-null    float64
 27  INCOME               108 non-null    int64
dtypes: float64(5), int64(2), object(21)
memory usage: 23.8+ KB

In [139]:
#practice of pandas.to_datetime() format
import pandas as pd

# 'invalid' cannot be parsed into a real date
data = {"col1": ['2025-06-21', 'invalid'],
        "col2": [3, 4]
        }
clean_data = data.copy()


# Using errors='coerce' turns 'invalid' into NaT instead of crashing:
result = pd.to_datetime(clean_data["col1"], errors='coerce')
print(result)

DatetimeIndex(['2025-06-21', 'NaT'], dtype='datetime64[ns]', freq=None)

In [140]:
df =pd.DataFrame(data)
df

         col1  col2
0  2025-06-21     3
1     invalid     4

In [141]:
clean_data["col1"] = pd.to_datetime(clean_data["col1"], errors='coerce')
clean_df = pd.DataFrame(clean_data)
clean_df

        col1  col2
0 2025-06-21     3
1        NaT     4

In [142]:
patient_df.info() #this gives information of the file you have read-i. you can used this to tell if the file. there are 108 rows and for DEATHDATE THERE ARE 9 non-null so there are 99 missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   108 non-null    object
 1   BIRTHDATE            108 non-null    object
 2   DEATHDATE            9 non-null      object
 3   SSN                  108 non-null    object
 4   DRIVERS              85 non-null     object
 5   PASSPORT             78 non-null     object
 6   PREFIX               82 non-null     object
 7   FIRST                108 non-null    object
 8   MIDDLE               82 non-null     object
 9   LAST                 108 non-null    object
 10  SUFFIX               1 non-null      object
 11  MAIDEN               19 non-null     object
 12  MARITAL              65 non-null     object
 13  RACE                 108 non-null    object
 14  ETHNICITY            108 non-null    object
 15  GENDER               108 non-null    object
 16  BIRTHPLACE           108 non-null    object
 17  ADDRESS              108 non-null    object
 18  CITY                 108 non-null    object
 19  STATE                108 non-null    object
 20  COUNTY               108 non-null    object
 21  FIPS                 87 non-null     float64
 22  ZIP                  108 non-null    int64
 23  LAT                  108 non-null    float64
 24  LON                  108 non-null    float64
 25  HEALTHCARE_EXPENSES  108 non-null    float64
 26  HEALTHCARE_COVERAGE  108 non-null    float64
 27  INCOME               108 non-null    int64
dtypes: float64(5), int64(2), object(21)
memory usage: 23.8+ KB

In [143]:
patient_df.head()# this gives the top 5 rows

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,a1733070-046a-4506-bba6-47f32652e9d7,1979-02-20,NaN,999-14-9549,S99994775,X74721768X,Mr.,Donte636,Elmo857,Daugherty69,...,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400
1,f9ba83f7-9940-16ae-0854-24bd34bf1843,1971-11-23,NaN,999-86-7840,S99961203,X51581530X,Mrs.,Ashlee14,Catrina144,Tromp100,...,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948
2,fc2d1fb9-862d-a60c-581a-519f5470d866,1975-09-16,NaN,999-93-4967,S99920007,X43158821X,Mrs.,Eartha927,Leanora120,Kulas532,...,Wakefield,Massachusetts,Middlesex County,25017.0,1880,42.483985,-71.034461,499804.16,1376278.98,77604
3,5a1b2463-6dbf-ff69-4ab9-fbc24841b9fd,2005-10-30,2008-03-09,999-90-2978,NaN,NaN,NaN,Ariadna374,Isabel214,Fernández399,...,Revere,Massachusetts,Suffolk County,25025.0,2151,42.372662,-70.954338,872.39,41094.85,26313
4,50834d5b-3074-9f8b-833e-e32a1004126d,1980-07-12,NaN,999-14-3925,S99972845,X90441215X,Mr.,Jesse626,Brendan864,Carter549,...,Quincy,Massachusetts,Norfolk County,25021.0,2169,42.317311,-71.054110,72235.91,15613.10,78102

In [144]:
patient_df.head()

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,a1733070-046a-4506-bba6-47f32652e9d7,1979-02-20,NaN,999-14-9549,S99994775,X74721768X,Mr.,Donte636,Elmo857,Daugherty69,...,Boston,Massachusetts,Suffolk County,25025.0,2124,42.354249,-71.068778,12223.69,173583.25,16400
1,f9ba83f7-9940-16ae-0854-24bd34bf1843,1971-11-23,NaN,999-86-7840,S99961203,X51581530X,Mrs.,Ashlee14,Catrina144,Tromp100,...,Barnstable,Massachusetts,Barnstable County,25001.0,2673,41.706016,-70.311956,539230.03,737140.75,93948
2,fc2d1fb9-862d-a60c-581a-519f5470d866,1975-09-16,NaN,999-93-4967,S99920007,X43158821X,Mrs.,Eartha927,Leanora120,Kulas532,...,Wakefield,Massachusetts,Middlesex County,25017.0,1880,42.483985,-71.034461,499804.16,1376278.98,77604
3,5a1b2463-6dbf-ff69-4ab9-fbc24841b9fd,2005-10-30,2008-03-09,999-90-2978,NaN,NaN,NaN,Ariadna374,Isabel214,Fernández399,...,Revere,Massachusetts,Suffolk County,25025.0,2151,42.372662,-70.954338,872.39,41094.85,26313
4,50834d5b-3074-9f8b-833e-e32a1004126d,1980-07-12,NaN,999-14-3925,S99972845,X90441215X,Mr.,Jesse626,Brendan864,Carter549,...,Quincy,Massachusetts,Norfolk County,25021.0,2169,42.317311,-71.054110,72235.91,15613.10,78102

In [145]:
# variable_1 = "chocolate","vanilla","red velvet","strawberry"
flavour_list = list(("chocolate","vanilla","red velvet","strawberry"))
print(flavour_list[0:3])

flavour_list_01 = ["chocolate","vanilla","red velvet","strawberry"]
print(flavour_list_01)

['chocolate', 'vanilla', 'red velvet']
['chocolate', 'vanilla', 'red velvet', 'strawberry']